name: "pwn-demo"
description: "A demo for pwn challenges"
type: "socket" # or "web"
flag: "flag{demo_pwn_flag}"
flag_type: "combined" # or "static", "suffix", "leetify", "capitalize"
duration: 1800 # currently unused
repository: "oci://registry:5000/charts"
chart: "pwn" # The same as the charts folder name
chart_version: "0.1.0"
values: |
  image.repository=ghcr.io/dragonsecsi/dctfsi-2025/pwn/flagmanager
  image.tag=latest
  image.pullPolicy=Always
  imagePullSecrets[0].name=ghcr
  flag.envkey=FLAG_DEMO
  flag.path.key=flag.txt
  flag.path.dest=/app/flag.txt
