image:
  repository: ghcr.io/dragonsecsi/dctfsi-2025/web/bakery
  pullPolicy: Always
  tag: latest

imagePullSecrets:
  - name: ghcr

pod:
  annotations: {}
  labels: {}
  port: 8000
  env: []
  # Example
  #  - name: "DEMO"
  #    value: "demo"
  securityContext:
    runAsNonRoot: true
    runAsUser: 1337
    runAsGroup: 1337
    fsGroup: 1337
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi

deployment:
  annotations: {}
  labels: {}

service:
  annotations: {}
  labels: {}
  type: ClusterIP
  port: 80

httproute:
  annotations: {}
  labels: {}
  hostSuffix: "web.vuln.si"
  gateway: "vuln"
  httpSectionName: "http-web"
  httpsSectionName: "https-web"

volumes: []
  # Example
  # - name: "db"
  #   path: "/app/db"
  #   size: "50Mi"

flag:
  flag: "flag{unset}"
  envkey: "FLAG" # If set, the flag will be injected to this environment variable
  path: # If set, the flag will be written to this file path. To disable, set to {}
    key: "flag.txt"
    dest: "/app/flag.txt" # Suffix must be the same as key
